#!/bin/bash
BASEDIR=$PWD
. $BASEDIR/io.sh 1 1 14 "$@"
CURDIR=`pwd`
set -e
## INPUTS VARIABLES
txtinout_zip=${INPUTS1}


## PARAMETERS VARIABLES
p1=${PARAMS1}


set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT


pushd TxtInOut
./swat670
popd


####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
set -e
cd $BASEDIR
. $BASEDIR/output.sh